### ISSUE TITLE
[Improvement] Get rid of opacity:0 hack on select, use cleaner solution.

### ISSUE THREAD

**Issue by wujekbogdan** [dbushell/Pikaday#351]
I see that `select` has `opacity` set to `0` and `position` set to `absolute` in order to show the dropdown when `.pika-label` is clicked.
It works fine, but there is a cleaner solution. It' accessible for screen readers and makes creating custom themes easier. Using this solution we don't have to worry about positioning when we change labels font-size, margins, etc.

The solution:
1. get rid of **all** `select` styles,
3. replace the styles with:
``` css
.pika-title select {
    /* make it hidden: It's a popular "hack", used for example in Bootstrap 3 (.sr-only class); */
    display: block;
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
}

.pika-title select:focus {
    /* reset default select styles on focus */
    width: 100%;
    margin: 0;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    height: auto;
    clip: auto;

    /* set opacity to 0, to keep select visually hidden. it will not affect options! */
    opacity: 0;
}
```
5. replace a `<div class="pika-label>"` with a regular label `<label class="pika-label">
6. When we click the label, select gets focus (because this is how label works ;)), :focus styles are applied and dropdown shows up. Simple and clean. **TA-DA!**
