### ISSUE TITLE
IE8 <select> opacity

### ISSUE THREAD

**Issue by rocktronica** [dbushell/Pikaday#54]
How  do you feel about supporting opacity in IE8 w/ "filter"?

``` css
.pika-title select {
    /* .... */
    filter: alpha(opacity=0);
    opacity: 0;
}
```
